name: "Extract data download logs"

on:
  push:
    branches:
      - ainfeld
  #schedule:
  #  - cron: "0 0 * * 1"

jobs:
  aggregate-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
