name: "Extract download data logs"

#on:
#  push:
#    branches:
#      - ainfeld
  #schedule:
  #  - cron: "0 0 * * 1"

jobs:
  extract download data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt
      - name: Configure Prod AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
          role-to-assume: ${{ secrets.AWS_PROD_ROLE_TO_ASSUME }}
          role-duration-seconds: 900
      - name: Run download data script
        run: |
          python3 analytics/download_data_logs.py
